import { StyleSheet } from 'react-native';
import colors from '../../utils/colors';

const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: colors.background,
    },
    scrollContent: {
        flexGrow: 1,
        paddingHorizontal: 20,
        paddingTop: 12,
        paddingBottom: 20,
    },
    header: {
        minHeight: 48,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 13,
        marginBottom: 8,
    },
    backButton: {
        width: 25,
        height: 42,
        alignItems: 'flex-start',
        justifyContent: 'center',
    },
    heading: {
        flex: 1,
        color: colors.text,
        fontSize: 21,
        lineHeight: 27,
        fontWeight: '800',
        letterSpacing: -0.3,
    },
    subtitle: {
        color: colors.textSecondary,
        fontSize: 11,
        lineHeight: 17,
        marginBottom: 17,
    },
    identityRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 11,
        marginBottom: 18,
    },
    anonymousPill: {
        minWidth: 105,
        height: 29,
        paddingHorizontal: 12,
        borderRadius: 16,
        justifyContent: 'center',
        backgroundColor: colors.accent,
    },
    anonymousPillOff: {
        backgroundColor: colors.surface,
    },
    anonymousLabel: {
        color: colors.dark,
        fontSize: 10,
        fontWeight: '700',
    },
    anonymousLabelOff: {
        color: colors.textSecondary,
    },
    avatar: {
        width: 38,
        height: 38,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.accent,
    },
    authorName: {
        color: colors.text,
        fontSize: 13,
        fontWeight: '700',
    },
    composeInputCard: {
        minHeight: 191,
        borderRadius: 19,
        padding: 16,
        backgroundColor: colors.surface,
        marginBottom: 14,
    },
    thoughtInput: {
        flex: 1,
        minHeight: 132,
        color: colors.text,
        fontSize: 18,
        lineHeight: 26,
        textAlignVertical: 'top',
        padding: 0,
    },
    characterCount: {
        color: colors.textSecondary,
        fontSize: 10,
        marginTop: 8,
    },
    optionCard: {
        minHeight: 60,
        paddingHorizontal: 15,
        borderRadius: 15,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 13,
        backgroundColor: colors.surface,
        marginBottom: 9,
    },
    optionIcon: {
        width: 20,
        alignItems: 'center',
    },
    optionCopy: {
        flex: 1,
        gap: 3,
    },
    optionTitle: {
        color: colors.text,
        fontSize: 12,
        fontWeight: '700',
    },
    optionDescription: {
        color: colors.textSecondary,
        fontSize: 10,
        lineHeight: 14,
    },
    primaryButton: {
        minHeight: 47,
        paddingHorizontal: 16,
        borderRadius: 15,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: colors.accent,
    },
    primaryButtonDisabled: {
        opacity: 0.45,
    },
    bottomActions: {
        marginTop: 25,
    },
    primaryLabel: {
        color: colors.dark,
        fontSize: 13,
        fontWeight: '800',
    },
    secondaryButton: {
        minHeight: 46,
        paddingHorizontal: 15,
        borderRadius: 15,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: colors.surface,
        marginTop: 8,
    },
    secondaryLabel: {
        color: colors.text,
        fontSize: 12,
        fontWeight: '700',
    },
    landscape: {
        height: 190,
        borderRadius: 18,
        overflow: 'hidden',
        backgroundColor: colors.teal,
        marginBottom: 14,
    },
    landscapeSky: {
        ...StyleSheet.absoluteFill,
        backgroundColor: colors.teal,
    },
    landscapeSun: {
        position: 'absolute',
        width: 54,
        height: 54,
        borderRadius: 27,
        top: 24,
        right: 33,
        backgroundColor: colors.accent,
    },
    hillBack: {
        position: 'absolute',
        width: '120%',
        height: 132,
        left: '-10%',
        bottom: 10,
        borderTopLeftRadius: 100,
        borderTopRightRadius: 110,
        backgroundColor: '#526F6C',
        transform: [{ rotate: '-7deg' }],
    },
    hillFront: {
        position: 'absolute',
        width: '120%',
        height: 76,
        left: '-7%',
        bottom: -16,
        borderTopLeftRadius: 100,
        borderTopRightRadius: 100,
        backgroundColor: '#183231',
        transform: [{ rotate: '-3deg' }],
    },
    landscapePath: {
        position: 'absolute',
        width: 58,
        height: 54,
        left: '42%',
        bottom: 2,
        borderTopWidth: 9,
        borderRightWidth: 9,
        borderColor: colors.accentMuted,
        borderTopRightRadius: 30,
        transform: [{ rotate: '26deg' }],
    },
    privacyNote: {
        color: colors.textSecondary,
        fontSize: 10,
        lineHeight: 15,
        marginVertical: 8,
    },
    originalCard: {
        borderRadius: 17,
        padding: 15,
        backgroundColor: colors.surface,
        marginBottom: 13,
    },
    cardEyebrow: {
        color: colors.accent,
        fontSize: 10,
        fontWeight: '700',
        marginBottom: 10,
    },
    originalText: {
        color: colors.text,
        fontSize: 15,
        lineHeight: 22,
    },
    toolRow: {
        flexDirection: 'row',
        gap: 6,
        marginBottom: 16,
    },
    tool: {
        flex: 1,
        minHeight: 31,
        borderRadius: 17,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.surface,
    },
    activeTool: {
        backgroundColor: colors.accent,
    },
    toolLabel: {
        color: colors.textSecondary,
        fontSize: 10,
        fontWeight: '600',
    },
    activeToolLabel: {
        color: colors.dark,
    },
    suggestionCard: {
        minHeight: 151,
        borderRadius: 18,
        padding: 16,
        backgroundColor: colors.surface,
        marginBottom: 12,
    },
    suggestionText: {
        color: colors.text,
        fontSize: 18,
        lineHeight: 25,
        marginTop: 12,
    },
    footnote: {
        color: colors.textSecondary,
        fontSize: 10,
        lineHeight: 15,
        marginBottom: 16,
    },
    previewCard: {
        borderRadius: 19,
        padding: 15,
        backgroundColor: colors.surface,
        marginBottom: 12,
    },
    previewHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 14,
    },
    previewAvatar: {
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.lavender,
    },
    previewMeta: {
        flex: 1,
        gap: 3,
    },
    previewName: {
        color: colors.text,
        fontSize: 12,
        fontWeight: '700',
    },
    previewHandle: {
        color: colors.textSecondary,
        fontSize: 9,
    },
    previewCaption: {
        color: colors.text,
        fontSize: 20,
        lineHeight: 27,
        marginBottom: 20,
    },
    previewTags: {
        color: colors.textSecondary,
        fontSize: 10,
        marginBottom: 15,
    },
    previewActions: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    audience: {
        minHeight: 56,
        paddingHorizontal: 14,
        borderRadius: 15,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        backgroundColor: colors.surface,
        marginBottom: 15,
    },
});

export default styles;
