import { StyleSheet } from 'react-native';
import colors from '../../utils/colors';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 24,
  },
  header: {
    minHeight: 43,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
    marginBottom: 10,
  },
  backButton: {
    width: 27,
    height: 40,
    justifyContent: 'center',
  },
  title: {
    color: colors.text,
    fontSize: 21,
    lineHeight: 28,
    fontWeight: '800',
  },
  headerAction: {
    marginLeft: 'auto',
    padding: 8,
  },
  profile: {
    alignItems: 'center',
    paddingTop: 10,
  },
  avatar: {
    width: 86,
    height: 86,
    borderRadius: 43,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.lavender,
    marginBottom: 13,
  },
  ownAvatar: {
    backgroundColor: colors.accent,
  },
  displayName: {
    color: colors.text,
    fontSize: 21,
    lineHeight: 27,
    fontWeight: '800',
  },
  username: {
    color: colors.textSecondary,
    fontSize: 11,
    marginTop: 3,
  },
  bio: {
    maxWidth: 270,
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
    marginTop: 14,
  },
  stats: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 20,
    marginBottom: 19,
  },
  stat: {
    alignItems: 'center',
    gap: 4,
  },
  statValue: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  statLabel: {
    color: colors.textSecondary,
    fontSize: 10,
  },
  actions: {
    width: '100%',
    flexDirection: 'row',
    gap: 10,
    marginBottom: 19,
  },
  followButton: {
    flex: 1,
    minHeight: 45,
    paddingHorizontal: 14,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.accent,
  },
  followingButton: {
    backgroundColor: colors.surface,
  },
  followLabel: {
    color: colors.dark,
    fontSize: 13,
    fontWeight: '800',
  },
  followingLabel: {
    color: colors.text,
  },
  messageButton: {
    flex: 1,
    minHeight: 45,
    paddingHorizontal: 14,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surface,
  },
  messageLabel: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  editProfileButton: {
    width: '100%',
    minHeight: 46,
    paddingHorizontal: 15,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surface,
    marginBottom: 19,
  },
  editProfileLabel: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '700',
  },
  tabs: {
    flexDirection: 'row',
    gap: 7,
    marginBottom: 15,
  },
  tab: {
    flex: 1,
    height: 31,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  activeTab: {
    backgroundColor: colors.accent,
  },
  tabLabel: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: '700',
  },
  activeTabLabel: {
    color: colors.dark,
  },
  postCard: {
    borderRadius: 18,
    padding: 13,
    backgroundColor: colors.surface,
    marginBottom: 12,
  },
  postHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    marginBottom: 13,
  },
  postAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.lavender,
  },
  postIdentity: {
    flex: 1,
    gap: 3,
  },
  postAuthor: {
    color: colors.text,
    fontSize: 11,
    fontWeight: '700',
  },
  postMeta: {
    color: colors.textSecondary,
    fontSize: 9,
  },
  postCaption: {
    color: colors.text,
    fontSize: 16,
    lineHeight: 22,
    marginBottom: 14,
  },
  postTags: {
    color: colors.textSecondary,
    fontSize: 9,
  },
  savedCaption: {
    color: colors.text,
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 5,
  },
  savedActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 15,
  },
  savedTip: {
    minWidth: 61,
    height: 32,
    borderRadius: 16,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    backgroundColor: colors.accent,
    marginLeft: 'auto',
  },
  savedTipLabel: {
    color: colors.dark,
    fontSize: 11,
    fontWeight: '700',
  },
  reelGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 10,
  },
  reelTile: {
    width: '48.5%',
    aspectRatio: 0.9,
    borderRadius: 17,
    overflow: 'hidden',
    backgroundColor: colors.teal,
  },
  alternateReelTile: {
    backgroundColor: colors.reelBackground,
  },
  reelSun: {
    position: 'absolute',
    width: 38,
    height: 38,
    top: 18,
    right: 15,
    borderRadius: 19,
    backgroundColor: colors.lavender,
  },
  reelHillBack: {
    position: 'absolute',
    width: '125%',
    height: '44%',
    left: '-12%',
    bottom: '18%',
    borderTopLeftRadius: 90,
    borderTopRightRadius: 90,
    backgroundColor: colors.reelHill,
    transform: [{ rotate: '-8deg' }],
  },
  reelHillFront: {
    position: 'absolute',
    width: '125%',
    height: '27%',
    left: '-12%',
    bottom: '-3%',
    borderTopLeftRadius: 80,
    borderTopRightRadius: 80,
    backgroundColor: colors.reelHillShadow,
    transform: [{ rotate: '-4deg' }],
  },
  reelPath: {
    position: 'absolute',
    width: 35,
    height: 48,
    left: '44%',
    bottom: 4,
    borderTopWidth: 6,
    borderRightWidth: 6,
    borderColor: colors.reelPath,
    borderTopRightRadius: 24,
    transform: [{ rotate: '25deg' }],
  },
  reelPlayIcon: {
    position: 'absolute',
    right: 11,
    bottom: 11,
    width: 26,
    height: 26,
    borderWidth: 1,
    borderColor: colors.text,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  savedSubtitle: {
    color: colors.textSecondary,
    fontSize: 11,
    marginTop: -4,
    marginBottom: 18,
  },
  savedFilters: {
    flexDirection: 'row',
    gap: 7,
    marginBottom: 16,
  },
  savedFilter: {
    flex: 1,
    height: 32,
    borderRadius: 17,
    justifyContent: 'center',
    paddingHorizontal: 12,
    backgroundColor: colors.surface,
  },
  activeSavedFilter: {
    backgroundColor: colors.accent,
  },
  savedFilterLabel: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: '700',
  },
  activeSavedFilterLabel: {
    color: colors.dark,
  },
  savedArtwork: {
    height: 148,
    borderRadius: 15,
    overflow: 'hidden',
    backgroundColor: colors.teal,
    marginBottom: 11,
  },
  savedArtworkSun: {
    position: 'absolute',
    width: 39,
    height: 39,
    top: 18,
    right: 28,
    borderRadius: 20,
    backgroundColor: colors.accent,
  },
  savedHillBack: {
    position: 'absolute',
    width: '120%',
    height: 87,
    left: '-10%',
    bottom: 25,
    borderTopLeftRadius: 90,
    borderTopRightRadius: 90,
    backgroundColor: colors.reelHill,
    transform: [{ rotate: '-7deg' }],
  },
  savedHillFront: {
    position: 'absolute',
    width: '120%',
    height: 57,
    left: '-8%',
    bottom: -15,
    borderTopLeftRadius: 80,
    borderTopRightRadius: 80,
    backgroundColor: colors.reelHillShadow,
    transform: [{ rotate: '-3deg' }],
  },
  savedPath: {
    position: 'absolute',
    width: 48,
    height: 40,
    left: '44%',
    bottom: 0,
    borderTopWidth: 8,
    borderRightWidth: 8,
    borderColor: colors.accentMuted,
    borderTopRightRadius: 25,
    transform: [{ rotate: '25deg' }],
  },
  savedCollection: {
    minHeight: 61,
    paddingHorizontal: 14,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: colors.surface,
    marginTop: 5,
  },
  playIcon: {
    position: 'absolute',
    right: 13,
    bottom: 12,
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#10161788',
  },
  emptyState: {
    minHeight: 170,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    gap: 10,
  },
  emptyLabel: {
    color: colors.textSecondary,
    fontSize: 12,
  },
});

export default styles;
