import { StyleSheet } from 'react-native';
import colors from '../../utils/colors';

const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: colors.background,
    },
    content: {
        paddingHorizontal: 20,
        paddingTop: 12,
        paddingBottom: 18,
    },
    header: {
        minHeight: 48,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    brand: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 11,
    },
    brandMark: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.accent,
    },
    brandName: {
        color: colors.text,
        fontSize: 21,
        lineHeight: 24,
        fontWeight: '800',
    },
    tagline: {
        color: colors.textSecondary,
        fontSize: 10,
        lineHeight: 14,
    },
    headerActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 22,
        paddingRight: 4,
    },
    searchBox: {
        height: 43,
        borderRadius: 22,
        backgroundColor: colors.surface,
        paddingHorizontal: 14,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    searchInput: {
        flex: 1,
        color: colors.text,
        fontSize: 12,
        paddingVertical: 0,
    },
    filters: {
        flexDirection: 'row',
        gap: 7,
        marginTop: 13,
        marginBottom: 14,
    },
    filter: {
        flex: 1,
        height: 34,
        justifyContent: 'center',
        paddingHorizontal: 11,
        borderRadius: 18,
        backgroundColor: colors.surface,
    },
    selectedFilter: {
        backgroundColor: colors.accent,
    },
    filterLabel: {
        color: colors.textSecondary,
        fontSize: 11,
        fontWeight: '600',
    },
    selectedFilterLabel: {
        color: colors.dark,
    },
    post: {
        borderRadius: 21,
        padding: 13,
        backgroundColor: colors.surface,
    },
    postHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 11,
    },
    author: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    authorAvatar: {
        width: 38,
        height: 38,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.lavender,
    },
    authorName: {
        color: colors.text,
        fontSize: 13,
        lineHeight: 17,
        fontWeight: '700',
    },
    authorMeta: {
        color: colors.textSecondary,
        fontSize: 10,
        lineHeight: 14,
    },
    postArtwork: {
        width: '100%',
        aspectRatio: 1.75,
        borderRadius: 17,
        overflow: 'hidden',
        backgroundColor: colors.teal,
    },
    postCaption: {
        color: colors.text,
        fontSize: 12,
        lineHeight: 17,
        marginTop: 9,
    },
    postTags: {
        color: colors.textSecondary,
        fontSize: 10,
        lineHeight: 14,
        marginTop: 3,
    },
    postActions: {
        minHeight: 39,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 7,
    },
    socialActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 13,
    },
    postAction: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    actionCount: {
        color: colors.textSecondary,
        fontSize: 10,
    },
    tipButton: {
        minWidth: 59,
        height: 28,
        borderRadius: 14,
        paddingHorizontal: 9,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 5,
        backgroundColor: colors.accent,
    },
    tipLabel: {
        color: colors.dark,
        fontSize: 11,
        fontWeight: '700',
    },
    repliesSection: {
        paddingHorizontal: 5,
        paddingTop: 23,
    },
    repliesHeading: {
        color: colors.text,
        fontSize: 17,
        lineHeight: 22,
        fontWeight: '700',
        marginBottom: 20,
    },
    repliesList: {
        gap: 25,
    },
    replyItem: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 13,
    },
    replyAvatar: {
        width: 39,
        height: 39,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    replyContent: {
        flex: 1,
        paddingTop: 1,
    },
    replyAuthor: {
        color: colors.text,
        fontSize: 13,
        lineHeight: 17,
        fontWeight: '700',
        marginBottom: 5,
    },
    replyMessage: {
        color: colors.textSecondary,
        fontSize: 14,
        lineHeight: 21,
    },
    replyAction: {
        alignSelf: 'flex-start',
        paddingVertical: 7,
    },
    replyActionText: {
        color: colors.accent,
        fontSize: 11,
        lineHeight: 15,
    },
    replyComposer: {
        height: 49,
        paddingHorizontal: 16,
        borderRadius: 26,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        backgroundColor: colors.surface,
        marginTop: 24,
        marginBottom: 4,
    },
    replyInput: {
        flex: 1,
        color: colors.text,
        fontSize: 14,
        paddingVertical: 0,
    },
    aiCard: {
        minHeight: 78,
        borderRadius: 19,
        marginTop: 15,
        paddingHorizontal: 17,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 13,
        backgroundColor: colors.surface,
    },
    aiCopy: {
        gap: 4,
    },
    aiTitle: {
        color: colors.text,
        fontSize: 13,
        fontWeight: '700',
    },
    aiDescription: {
        color: colors.textSecondary,
        fontSize: 11,
    },
})

export default styles;

export const reelsStyles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: colors.background,
    },
    stage: {
        flex: 1,
        overflow: 'hidden',
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        backgroundColor: colors.reelBackground,
    },
    background: StyleSheet.absoluteFill,
    topBar: {
        zIndex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        paddingTop: 22,
    },
    heading: {
        color: colors.text,
        fontSize: 29,
        lineHeight: 36,
        fontWeight: '800',
        letterSpacing: -0.5,
    },
    followingChip: {
        width: 134,
        height: 37,
        paddingHorizontal: 13,
        borderRadius: 20,
        alignItems: 'flex-start',
        justifyContent: 'center',
        backgroundColor: colors.surface,
    },
    followingLabel: {
        color: colors.textSecondary,
        fontSize: 12,
        fontWeight: '600',
    },
    orb: {
        position: 'absolute',
        top: '15%',
        right: 1,
        backgroundColor: colors.lavender,
    },
    actionRail: {
        position: 'absolute',
        right: 18,
        top: '39%',
        zIndex: 2,
        alignItems: 'center',
        gap: 24,
    },
    action: {
        minWidth: 38,
        alignItems: 'center',
        gap: 7,
    },
    actionLabel: {
        color: colors.text,
        fontSize: 11,
        lineHeight: 15,
    },
    captionBlock: {
        position: 'absolute',
        zIndex: 1,
        left: 24,
        right: 78,
        bottom: 26,
        alignItems: 'flex-start',
    },
    title: {
        color: colors.text,
        fontSize: 22,
        lineHeight: 28,
        fontWeight: '800',
        letterSpacing: -0.4,
        marginBottom: 19,
    },
    creatorRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 11,
    },
    avatar: {
        width: 42,
        height: 42,
        borderRadius: 22,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.lavender,
    },
    creatorCopy: {
        gap: 4,
    },
    creatorName: {
        color: colors.text,
        fontSize: 13,
        fontWeight: '700',
    },
    creatorDescription: {
        color: colors.text,
        fontSize: 11,
        lineHeight: 16,
    },
    tipButton: {
        minWidth: 123,
        height: 36,
        marginTop: 20,
        paddingHorizontal: 14,
        borderRadius: 20,
        justifyContent: 'center',
        backgroundColor: colors.accent,
    },
    tipButtonPressed: {
        opacity: 0.82,
    },
    tipLabel: {
        color: colors.dark,
        fontSize: 12,
        fontWeight: '700',
    },
});
