import { StyleSheet } from 'react-native';
import colors from '../../utils/colors';

const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: colors.background,
    },
    screen: {
        flex: 1,
        paddingHorizontal: 20,
        paddingTop: 9,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 13,
        marginBottom: 4,
    },
    backButton: {
        width: 28,
        height: 42,
        justifyContent: 'center',
    },
    title: {
        color: colors.text,
        fontSize: 23,
        lineHeight: 30,
        fontWeight: '800',
        letterSpacing: -0.5,
    },
    subtitle: {
        color: colors.textSecondary,
        fontSize: 12,
        lineHeight: 18,
        marginBottom: 10,
    },
    content: {
        flexGrow: 1,
        paddingTop: 2,
        paddingBottom: 14,
    },
    emptyContent: {
        flexGrow: 1,
        justifyContent: 'center',
    },
    companion: {
        width: 160,
        height: 160,
        borderRadius: 28,
        alignSelf: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.reelBackground,
        marginBottom: 29,
    },
    compactCompanion: {
        width: 88,
        height: 88,
        borderRadius: 22,
        marginBottom: 4,
    },
    companionRing: {
        position: 'absolute',
        width: 116,
        height: 116,
        borderWidth: 1,
        borderColor: '#52615C',
        borderRadius: 58,
        alignItems: 'center',
        justifyContent: 'center',
    },
    compactRing: {
        width: 66,
        height: 66,
        borderRadius: 33,
    },
    companionFace: {
        width: 72,
        height: 72,
        borderRadius: 36,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.accent,
    },
    compactFace: {
        width: 43,
        height: 43,
        borderRadius: 22,
    },
    eyeRow: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 7,
    },
    eye: {
        width: 11,
        height: 4,
        borderRadius: 2,
        backgroundColor: colors.dark,
    },
    compactEye: {
        width: 7,
        height: 3,
    },
    mouth: {
        width: 27,
        height: 11,
        borderBottomLeftRadius: 14,
        borderBottomRightRadius: 14,
        backgroundColor: colors.dark,
    },
    compactMouth: {
        width: 17,
        height: 7,
    },
    orbitDot: {
        position: 'absolute',
        width: 18,
        height: 18,
        top: 27,
        right: 20,
        borderRadius: 9,
        backgroundColor: colors.lavender,
    },
    compactOrbitDot: {
        width: 11,
        height: 11,
        top: 15,
        right: 11,
    },
    smallDot: {
        position: 'absolute',
        width: 11,
        height: 11,
        left: 24,
        bottom: 37,
        borderRadius: 6,
        backgroundColor: colors.accent,
    },
    compactSmallDot: {
        width: 7,
        height: 7,
        left: 13,
        bottom: 20,
    },
    welcome: {
        color: colors.text,
        fontSize: 23,
        lineHeight: 30,
        fontWeight: '800',
        textAlign: 'center',
        marginBottom: 28,
    },
    suggestionList: {
        gap: 14,
    },
    suggestion: {
        minHeight: 75,
        paddingHorizontal: 17,
        paddingVertical: 12,
        borderRadius: 17,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 17,
        backgroundColor: colors.surface,
    },
    suggestionCopy: {
        flex: 1,
        gap: 5,
    },
    suggestionTitle: {
        color: colors.text,
        fontSize: 14,
        lineHeight: 18,
        fontWeight: '700',
    },
    suggestionDescription: {
        color: colors.textSecondary,
        fontSize: 11,
        lineHeight: 15,
    },
    conversation: {
        flexGrow: 1,
        paddingTop: 16,
        gap: 13,
    },
    message: {
        maxWidth: '88%',
        padding: 14,
        borderRadius: 17,
    },
    userMessage: {
        alignSelf: 'flex-end',
        borderBottomRightRadius: 5,
        backgroundColor: colors.surfaceRaised,
    },
    assistantMessage: {
        alignSelf: 'flex-start',
        borderBottomLeftRadius: 5,
        backgroundColor: colors.surface,
    },
    messageText: {
        color: colors.text,
        fontSize: 13,
        lineHeight: 19,
    },
    composer: {
        minHeight: 57,
        paddingHorizontal: 17,
        borderRadius: 18,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: colors.surface,
        marginBottom: 2,
    },
    composerInput: {
        flex: 1,
        minHeight: 48,
        color: colors.text,
        fontSize: 13,
        paddingVertical: 12,
    },
});

export default styles;
