import { StyleSheet } from 'react-native';
import colors from '../../utils/colors';

const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: colors.background,
    },
    content: {
        flexGrow: 1,
        paddingHorizontal: 22,
        paddingTop: 18,
        paddingBottom: 24,
    },
    header: {
        minHeight: 44,
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 22,
    },
    backButton: {
        width: 34,
        height: 40,
        alignItems: 'flex-start',
        justifyContent: 'center',
        marginRight: 8,
    },
    headerTitle: {
        flex: 1,
        color: colors.text,
        fontSize: 23,
        lineHeight: 29,
        fontWeight: '800',
        letterSpacing: -0.4,
    },
    searchBox: {
        height: 52,
        borderRadius: 27,
        backgroundColor: colors.surface,
        paddingHorizontal: 17,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 13,
        marginBottom: 31,
    },
    searchInput: {
        flex: 1,
        color: colors.text,
        fontSize: 14,
        paddingVertical: 0,
    },
    sectionTitle: {
        color: colors.text,
        fontSize: 18,
        lineHeight: 24,
        fontWeight: '700',
        marginBottom: 15,
    },
    trendingList: {
        gap: 10,
    },
    trendingCard: {
        minHeight: 75,
        paddingHorizontal: 18,
        borderRadius: 19,
        backgroundColor: colors.surface,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 17,
    },
    trendingCopy: {
        flex: 1,
        gap: 5,
    },
    trendingTag: {
        color: colors.text,
        fontSize: 14,
        lineHeight: 18,
        fontWeight: '700',
    },
    trendingVoices: {
        color: colors.textSecondary,
        fontSize: 12,
        lineHeight: 16,
    },
    moodHeading: {
        marginTop: 32,
        marginBottom: 18,
    },
    moods: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    moodChip: {
        width: '47%',
        height: 36,
        paddingHorizontal: 14,
        justifyContent: 'center',
        borderRadius: 20,
        backgroundColor: colors.surface,
    },
    selectedMoodChip: {
        backgroundColor: colors.accent,
    },
    moodLabel: {
        color: colors.textSecondary,
        fontSize: 12,
        fontWeight: '600',
    },
    selectedMoodLabel: {
        color: colors.dark,
    },
    results: {
        gap: 23,
    },
    resultTabs: {
        flexDirection: 'row',
        gap: 8,
    },
    resultTab: {
        flex: 1,
        height: 36,
        paddingHorizontal: 14,
        justifyContent: 'center',
        borderRadius: 20,
        backgroundColor: colors.surface,
    },
    selectedResultTab: {
        backgroundColor: colors.accent,
    },
    resultTabLabel: {
        color: colors.textSecondary,
        fontSize: 12,
        fontWeight: '600',
    },
    selectedResultTabLabel: {
        color: colors.dark,
    },
    postCard: {
        minHeight: 342,
        padding: 17,
        borderRadius: 23,
        backgroundColor: colors.surface,
    },
    postHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 27,
    },
    avatar: {
        width: 44,
        height: 44,
        borderRadius: 23,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.lavender,
    },
    authorCopy: {
        flex: 1,
        marginLeft: 12,
        gap: 3,
    },
    authorName: {
        color: colors.text,
        fontSize: 14,
        lineHeight: 18,
        fontWeight: '700',
    },
    authorMeta: {
        color: colors.textSecondary,
        fontSize: 11,
        lineHeight: 15,
    },
    postCategory: {
        color: colors.accent,
        fontSize: 12,
        lineHeight: 17,
        fontWeight: '700',
        marginBottom: 10,
    },
    postMessage: {
        color: colors.text,
        fontSize: 26,
        lineHeight: 35,
        letterSpacing: -0.3,
        minHeight: 91,
    },
    postTags: {
        color: colors.textSecondary,
        fontSize: 11,
        lineHeight: 16,
        marginTop: 20,
        marginBottom: 17,
    },
    postActions: {
        minHeight: 35,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    socialActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
    },
    socialAction: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    actionCount: {
        color: colors.textSecondary,
        fontSize: 11,
    },
    tipButton: {
        height: 34,
        minWidth: 72,
        paddingHorizontal: 11,
        borderRadius: 18,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 7,
        backgroundColor: colors.accent,
    },
    tipLabel: {
        color: colors.dark,
        fontSize: 12,
        fontWeight: '700',
    },
    reelResult: {
        overflow: 'hidden',
        paddingBottom: 14,
        borderRadius: 22,
        backgroundColor: colors.surface,
    },
    reelArtwork: {
        height: 250,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.reelBackground,
    },
    reelSun: {
        position: 'absolute',
        top: 30,
        right: 36,
        width: 110,
        height: 110,
        borderRadius: 55,
        backgroundColor: colors.lavender,
    },
    reelTitle: {
        color: colors.text,
        fontSize: 15,
        fontWeight: '700',
        marginHorizontal: 15,
        marginTop: 13,
    },
    reelMeta: {
        color: colors.textSecondary,
        fontSize: 11,
        marginHorizontal: 15,
        marginTop: 5,
    },
    personResult: {
        minHeight: 76,
        paddingHorizontal: 16,
        borderRadius: 20,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.surface,
    },
    followButton: {
        height: 32,
        paddingHorizontal: 13,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.accent,
    },
    followLabel: {
        color: colors.dark,
        fontSize: 12,
        fontWeight: '700',
    },
})

export default styles;
